//! Every command, in one list.
//!
//! Apart from `contract.rs` for the same reason `migrations_list.rs` is apart
//! from `migrations.rs`: one file holds a decision somebody has to read — why
//! the contract is separate from the invoke handler, where the generated
//! TypeScript lands — and the other holds a hundred and thirty names. A
//! decision buried under a list is a decision nobody finds.

use tauri_specta::{collect_commands, Builder};

use crate::{
    account, adopting, agent_choice, agent_profiles, arranging, asking, board, branches, card_chat,
    card_work, cards, chat, columns, commands, diffs, files, filetree, front, happening, history,
    in_flight, index, installations, mcp, moving, notices, openers, outside_sessions, panels,
    panes, pasting, paths, plan_limits, plugin_data, plugins, priming, projects, receipts, reveal,
    rewinding, runs_list, saves, search, session_search, sessions, settings, shell_launch, skills,
    slash, sources, spend_history, staging, steering, steps, threads, update, watching, workspace,
    worktree_base, worktrees, wsfiles,
};

/// Loads every command whose types are generated into TypeScript.
pub(super) fn loaded(builder: Builder<tauri::Wry>) -> Builder<tauri::Wry> {
    builder.commands(collect_commands![
        commands::app_info,
        commands::app_health,
        commands::app_capabilities,
        projects::project_list,
        projects::project_add,
        projects::project_clone,
        projects::project_open,
        projects::project_forget,
        projects::project_rename,
        chat::chat_history,
        threads::chat_list,
        outside_sessions::chat_outside,
        adopting::chat_adopt,
        plan_limits::plan_limits,
        update::update_check,
        update::update_download,
        spend_history::spend_history,
        card_chat::card_chat,
        rewinding::chat_rewind,
        runs_list::runs_list,
        session_search::sessions_search,
        steering::chat_cancel,
        steering::chat_stop_task,
        chat::chat_frames,
        panels::panel_widths,
        panels::panel_widths_write,
        agent_choice::agent_choice,
        agent_choice::agent_default_set,
        agent_choice::agent_enabled_set,
        agent_choice::agent_hooks_set,
        agent_profiles::agent_profiles,
        agent_profiles::agent_profile_save,
        agent_profiles::agent_profile_remove,
        chat::chat_attach,
        pasting::chat_paste,
        receipts::chat_receipt,
        slash::chat_slash_commands,
        asking::permission_answer,
        asking::permission_ask_from_now,
        asking::permission_questions,
        mcp::mcp_list,
        installations::cli_installations,
        skills::skills_list,
        skills::skills_read,
        workspace::workspace_read,
        workspace::usage_read,
        wsfiles::workspace_list,
        wsfiles::workspace_file,
        reveal::path_open,
        reveal::path_reveal,
        openers::apps_list,
        openers::apps_known,
        openers::apps_add,
        openers::apps_remove,
        openers::apps_open,
        worktrees::worktree_list,
        worktrees::worktree_remove,
        priming::worktree_prime_read,
        priming::worktree_prime_write,
        worktree_base::worktree_base_read,
        worktree_base::worktree_base_write,
        sources::worktree_sources,
        sources::worktree_source_show,
        filetree::project_tree,
        index::project_files,
        projects::project_changes,
        history::project_history,
        search::project_search,
        branches::branch_list,
        branches::branch_switch,
        projects::project_notes,
        projects::project_note_add,
        board::board_get,
        columns::column_create,
        columns::column_rename,
        columns::column_reorder,
        columns::column_delete,
        columns::column_set_step,
        columns::column_set_flow,
        board::card_create,
        board::card_update,
        moving::card_move,
        cards::card_detail,
        cards::card_set_due,
        cards::card_comment,
        cards::card_comment_edit,
        cards::card_comment_delete,
        cards::card_pin,
        cards::card_unpin,
        cards::card_board,
        card_work::card_checkout,
        card_work::card_terminal,
        card_work::card_play,
        notices::notices_read,
        notices::notices_mark,
        notices::notices_mark_all,
        notices::notices_sweep_due,
        files::file_read,
        paths::path_create,
        paths::path_move,
        paths::path_delete,
        staging::changes_stage,
        staging::changes_unstage,
        staging::changes_commit,
        staging::changes_discard,
        saves::file_write,
        diffs::file_diff,
        diffs::commit_diff,
        in_flight::run_cancel,
        front::card_archive,
        front::card_delete,
        front::card_restore,
        front::board_archived,
        front::card_diff,
        columns::step_create,
        steps::agents_list,
        sessions::terminal_attach_agent,
        sessions::session_ensure,
        sessions::session_layout,
        sessions::session_focus,
        arranging::session_split,
        arranging::session_close_leaf,
        arranging::session_close_tab,
        arranging::session_rename_leaf,
        arranging::session_set_ratio,
        panes::session_write,
        panes::session_resize,
        panes::pane_scrollback,
        panes::session_detach,
        shell_launch::session_running,
        watching::session_usage,
        shell_launch::agents_known,
        shell_launch::session_launch_agent,
        happening::terminal_happenings,
        happening::card_happenings,
        account::account_read,
        account::account_sign_in,
        account::account_poll,
        account::account_sign_out,
        settings::settings_read,
        settings::settings_write,
        settings::settings_finish_onboarding,
        plugins::plugin_list,
        plugins::plugin_set_enabled,
        plugins::plugin_install,
        plugins::plugin_uninstall,
        plugin_data::plugin_data_list,
        plugin_data::plugin_data_read,
        plugin_data::plugin_data_write,
        plugin_data::plugin_data_delete,
        plugin_data::plugin_data_pin,
    ])
}
