[package]
name = "devpit-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
devpit-core = { path = "../core" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
specta = { version = "=2.0.0-rc.25", features = ["derive"] }
